lanl/Fierro

tests-for-Explicit-Lagrange-Kokkos/input_for_Noh3D_test.cpp
tests-for-Explicit-Lagrange-Kokkos/input_for_NohRZ_test.cpp
tests-for-Explicit-Lagrange-Kokkos/input_for_Sedov3D_test.cpp
tests-for-Explicit-Lagrange-Kokkos/input_for_SedovRZ_test.cpp
tests-for-Explicit-Lagrange-Kokkos/input_for_TaylorAnvil3D_test.cpp
tests-for-Explicit-Lagrange-Kokkos/input_for_TaylorAnvilRZ_test.cpp
tests-for-Explicit-Lagrange-Kokkos/readme.txt

Optional directory for tests for Explicit-Lagrange-Kokkos. Contains instructions for running tests on specific version of Fierro and specific input files for tests.

Addition of benchmarked tests for Sedov, Noh, and Taylor Anvil

---

CLI/CMakeLists.txt
Parallel-Solvers/Parallel-Explicit/Eulerian_Solver/FEA_Module_Eulerian.cpp
Parallel-Solvers/Parallel-Explicit/SGH_Solver/FEA_Module_SGH.cpp
Yaml-Serializable/CMakeLists.txt

Changes related to building Fierro on Mac (M2) with Clang 13

Mac Build PR

---

src/Yaml-Serializable/README.md
src/Yaml-Serializable/include/type-discrimination.h
src/Yaml-Serializable/test/test.cpp

This is just adding a readme to the yaml-serializable library + minor enhancement to the `apply` functionality. 
All old tests + new tests are passing.

Yaml readme

---

src/EVP/src/CMakeLists.txt
src/EVP/src/init_state_vars.cpp
src/EVPFFT/src/Fierro-EVPFFT-Link/init_state_vars.cpp
src/LS-EVPFFT/src/Fierro-LS-EVPFFT-Link/init_state_vars.cpp
src/Parallel-Solvers/Material-Models/Ideal-Gas-Models/init_state_vars.cpp
src/Parallel-Solvers/Material-Models/User-Material-Models/init_state_vars.cpp
src/Parallel-Solvers/Material-Models/material_models.h
src/Parallel-Solvers/Parallel-Explicit/Dynamic_Elastic_Solver/FEA_Module_Dynamic_Elasticity.cpp
src/Parallel-Solvers/Parallel-Explicit/SGH_Solver/FEA_Module_SGH.cpp

Bug fix: added linkage to Elements for EVP
ENH: gave the user full control of the `state_vars` by removing the `const` in the function args. Now the user must update either the device or host after initializing `state_vars` in `init_state_vars` function.

Bug fix and enhancement

---

src/LS-EVPFFT/src/CMakeLists.txt
src/LS-EVPFFT/src/defgrad_dcmp.cpp
src/LS-EVPFFT/src/defgrad_dcmp.h

LS-EVPFFT Enhancement: added function to do polar decomposition.
Miroslav needs this.

added function to do polar decomposition

---

.github/PULL_REQUEST_TEMPLATE/Standard_pull_request_template.md

Adds a template to standardize pull request in a file structure that allows other templates to be added in the future. This will help streamline the review process. For more information see [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates).

Pull Request Templates

---

README.md

Adds instructions for contributing to Fierro to the README.

Update README.md to include contribution instructions

---

src/Parallel-Solvers/Parallel-Explicit/SGH_Solver/src/setup_sgh.cpp

- [ x] Bug fix (non-breaking change which fixes an issue)
* OS version:
* Hardware:
* Compiler:
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] The code builds from scratch with my new changes
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

BUG: prevent memory usage of TO structure

---

src/Parallel-Solvers/Parallel-Explicit/SGH_Solver/src/geometry.cpp
src/Parallel-Solvers/Parallel-Explicit/SGH_Solver/src/sgh_optimization.cpp

Fixes missing changes to the geometry file in the SGH solver and fixes a few style changes with MATAR parallel for loops. 
* OS version:
* Hardware:
* Compiler:

Fix missed geometry merge and some style stuff in optimization

---

src/Parallel-Solvers/Parallel-Explicit/SGH_Solver/src/force_gradients_sgh.cpp
src/Parallel-Solvers/Parallel-Explicit/example_sgh_optimization.yaml
src/Parallel-Solvers/Parallel-Explicit/example_simple.yaml

* OS version:
* Hardware:
* Compiler:

Fix q2 gradient term and move yaml file out of spurious directory

---

src/Parallel-Solvers/Solver.cpp

* OS version: WSL
* Hardware: Sapphire Rapids node
* Compiler: GCC

BUG: fix non overlap map construction when one rank has 0 entries

---

src/Parallel-Solvers/Parallel-Explicit/Example_Yaml_Scripts/taylor_anvil_opt.yaml
src/Parallel-Solvers/Simulation_Parameters/FEA_Module/Thermo_Elasticity_Parameters.h
src/Parallel-Solvers/Simulation_Parameters/Optimization_Options.h
src/Parallel-Solvers/Solver.cpp

* OS version: WSL2
* Hardware: Personal Desktop
* Compiler: GCC

Fix a compile bug for implicit solver due to a missing file push, expose another ROL option

---

.conda/elements/meta.yaml
.conda/evpfft-dev/cpu/meta.yaml
.conda/evpfft/cpu/meta.yaml
.conda/fierro-dev/cpu/meta.yaml
.conda/fierro-gui/meta.yaml
.conda/fierro/cpu/meta.yaml
.conda/heffte/cpu/meta.yaml
.conda/heffte/cuda/meta.yaml
.conda/trilinos/cpu/meta.yaml

Updates the name of the conda distributions.  Documentation update will be in next PR. 
* OS version:
* Hardware:
* Compiler:

ENH: Update names for conda distributions

---

.github/workflows/fierro-test-no-implicit.yml
.github/workflows/fierro-test.yml

This PR updates the conda workflow test files with the new names.  Will take a minute to get them all passing again, since they have to successfully publish, which is not always trivial. 
* OS version:
* Hardware:
* Compiler:

ENH: Fixes test for published conda packages

---

single-node-refactor/input.yaml
single-node-refactor/src/CMakeLists.txt
single-node-refactor/src/driver.cpp

A quick fix to compile code
* OS version:
* Hardware: X86 CPU and V100 GPU
* Compiler: gcc
yes to all

commented out SGTM_solver

---

single-node-refactor/input-impact-erosion.yaml
single-node-refactor/input-lattice.yaml
single-node-refactor/input-noh-rz.yaml
single-node-refactor/input-noh.yaml
single-node-refactor/input-origin-erosion.yaml
single-node-refactor/input-rz-polar.yaml
single-node-refactor/input-rz.yaml
single-node-refactor/input-sgtm-test.yaml
single-node-refactor/input.yaml
single-node-refactor/regression_tests/standard_inputs/Abaqus_read.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov_Erosion.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov_Read_Ensight.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov_rz_polar.yaml
single-node-refactor/regression_tests/standard_inputs/Sod_X.yaml
single-node-refactor/regression_tests/standard_inputs/Sod_Y.yaml
single-node-refactor/regression_tests/standard_inputs/Sod_Z.yaml
single-node-refactor/src/Solvers/SGH_solver_3D/src/force_sgh.cpp
single-node-refactor/src/Solvers/SGH_solver_rz/src/force_sgh_rz.cpp
single-node-refactor/src/common/include/material.h
single-node-refactor/src/input/parse_yaml.cpp
single-node-refactor/src/input/parse_yaml.h
single-node-refactor/src/material_models/artificial_viscosity/mars.h
single-node-refactor/src/material_models/artificial_viscosity/no_dissipation.h

Pulled out the MARS artificial viscosity from the force routines, making them just like other material models.  Additional artificial viscosity models can be added.
* OS version:  MacOs
* Compiler: clang
* OS version:  Linux
* Hardware: x86 and V100 GPU
* Compiler: gcc

refactoring dissipation models

---

single-node-refactor/input-impact-erosion.yaml
single-node-refactor/input-lattice.yaml
single-node-refactor/input-noh-rz.yaml
single-node-refactor/input-noh.yaml
single-node-refactor/input-origin-erosion.yaml
single-node-refactor/input-rz-polar.yaml
single-node-refactor/input-rz.yaml
single-node-refactor/input-sgtm-test.yaml
single-node-refactor/input.yaml
single-node-refactor/regression_tests/standard_inputs/Abaqus_read.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov_Erosion.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov_Read_Ensight.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov_rz_polar.yaml
single-node-refactor/regression_tests/standard_inputs/Sod_X.yaml
single-node-refactor/regression_tests/standard_inputs/Sod_Y.yaml
single-node-refactor/regression_tests/standard_inputs/Sod_Z.yaml
single-node-refactor/src/common/include/region.h
single-node-refactor/src/input/parse_yaml.cpp

Making improvements to region syntax in the yaml input file
- [X ] Test A :  Regression tests with OpenMP on a Mac
- [X ] Test B :  Ran input files in repo
* OS version: Mac OS 
* Hardware: X86 cpu
* Compiler: clang

Region Syntax Improvements

---

scripts/trilinos-install.sh
src/Parallel-Solvers/Implicit-Lagrange/FEA_Physics_Modules/DriverCore.hpp

Clone Trilinos release version 16
* OS version: WSL2
* Hardware: Desktop
* Compiler: GCC

ENH: stabilize Trilinos to release version 16

---

single-node-refactor/example_inputs/input-rz-vtu-out.yaml
single-node-refactor/example_inputs/input-vtu-out.yaml
single-node-refactor/src/common/include/mesh_io.h

Fixed a bug with writing 2D vtk files, added some example inputs (2D and 3D) for writing a vtk visualization output, and made the element type in the outputs based on linear elements or high-order elements for better performance. 
* OS version:  MacOS
* Compiler: clang++

VTK Outputs

---

single-node-refactor/example_inputs/input-impact-erosion.yaml
single-node-refactor/src/common/include/mesh_io.h

Fixed bug with removing old files in vtk outputs
* OS version: Mac
* Compiler: clang++
- [] I have added tests that prove my fix is effective or that my feature works

fixed graphics file I/O bug

---

single-node-refactor/src/common/include/mesh_io.h

Fixed the time information in the paraview output file. 
* OS version: Mac
* Compiler: clang++

fixed time information in paraview outputs

---

src/Parallel-Solvers/Parallel-Explicit/Topology_Optimization/Kinetic_Energy_Minimize_Shape_Opt.h

* OS version:
* Hardware:
* Compiler:

COMP: fix variable names

---

single-node-refactor/scripts/build-fierro.sh
single-node-refactor/scripts/cmake_build.sh
single-node-refactor/scripts/kokkos-install.sh
single-node-refactor/scripts/matar-install.sh

Minor tweak to name of valid options for debug flag. 
* OS version: Redhat
* Hardware:
* Compiler:

STYLE: Renaming debug flag to enabled or disabled
