src/EVPFFT/README.md
src/EVPFFT/example_input_files/example_evpfft_fierro_inputfile.txt
src/EVPFFT/example_input_files/example_evpfft_standalone_inputfile.txt
src/EVPFFT/example_input_files/lattice_input_files/evpfft_lattice_input.txt
src/EVPFFT/src/CMakeLists.txt
src/EVPFFT/src/allocate_memory.cpp
src/EVPFFT/src/command_line_args.cpp
src/EVPFFT/src/command_line_args.h
src/EVPFFT/src/data_crystal.cpp
src/EVPFFT/src/evpal.cpp
src/EVPFFT/src/evpfft.cpp
src/EVPFFT/src/evpfft.h
src/EVPFFT/src/vpsc_input.cpp

Removed compile time arrays and evpfft can be compiled without the need for 
-D NPHMX
-D NMODMX
-D NTWMMX
-D NSYSMX
in the cmake flag. instead these variables can be passed into the input file.

removed all compile time arrays

---

src/EVPFFT/README.md
src/EVPFFT/scripts/build-scripts/build_evpfft.sh
src/EVPFFT/scripts/install-scripts/install_heffte.sh
src/EVPFFT/scripts/install-scripts/install_kokkos.sh
src/EVPFFT/scripts/machines/darwin-env.sh
src/EVPFFT/scripts/machines/mac-env.sh

I have Added the machine options to EVPFFT/scripts, taken from @djdunning branch, while maintaining the interdependence of the scripts.
I also did some cleanup of the kokkos build types according to his branch.
Additionally, `==` was replaced with `=` where needed to allow comparability with macs

Added machine options to EVPFFT/scripts

---

src/CLI/include/FierroParallelBackends.hpp
src/CLI/include/MeshBuilderBackend.hpp
src/CLI/include/backend.hpp
src/CLI/src/main.cpp
src/CMakeLists.txt
src/Mesh-Builder/CMakeLists.txt
src/Mesh-Builder/include/IOUtilities.h
src/Mesh-Builder/include/Mesh.h
src/Mesh-Builder/include/MeshBuilder.h
src/Mesh-Builder/include/MeshBuilderInput.h
src/Mesh-Builder/include/MeshIO.h
src/Mesh-Builder/include/VtkIO.h
src/Mesh-Builder/src/EnsightIO.cpp
src/Mesh-Builder/src/MeshBuilder.cpp
src/Mesh-Builder/src/VtkIO.cpp
src/Mesh-Builder/src/main.cpp
src/Mesh-Builder/test/test.cpp
src/Parallel-Solvers/Parallel-Explicit/CMakeLists.txt
src/Yaml-Serializable/include/type-discrimination.h
src/Yaml-Serializable/include/yaml-serializable-containers.h

This PR takes the functionality that was previously in lanl/ELEMENTS/mesh_tools/mesh_builder.cpp and integrates it into the Fierro repo + fierro CLI.
* The previous implementation on the ELEMENTS repo incorrectly handled reading high order VTK meshes. Nathaniel had this fix on his local branch, but didn't push it.
* The previous implementation didn't correctly handle full cylinders (not that it was necessarily expected to). If a cylinder covered the full 360 degrees, it would not connect the ends cyclically, and instead have duplicate points and unconnected elements.
* Yaml-serialization didn't correctly support multiple inheritance when using type discriminators. Now it does. 
* Yaml.cpp only technically supports YAML V1.0, which doesn't include inline. bracket closed lists. (e.g. [1, 2, …

Mesh builder

---

Anaconda-Packages/evpfft/cpu/meta.yaml
src/Parallel-Solvers/Parallel-Explicit/Simulation_Parameters_Base.h
src/Parallel-Solvers/Parallel-Explicit/example_simple.yaml

Previously we left this line in the parameter processing:
```
sie = (963.652344 * std::pow((1.2 / 30.0), 3)) / std::pow(radius2.value(), 3);
```
This is a specific energy that was intended for a specific discretization of the Sedov problem. Not really appropriate for general use, especially *all cylinders/spheres*, which it was used for.
We are no longer defaulting the energy under any circumstances. And we have added an alternative, potentially more intuitive method for specifying the energy. 
The current value comes from the analytic solution of the Sedov problem intended to have a peak compression at T~=1. The value 963 * std::pow((1.2 / 30.0), 3)) * 4/3 PI is the total energy contained in the region, which comes out to be ~= 0.2583. 
Now we allow for the specification of SIE or IE …

Remove hard coded input energy

---

Anaconda-Packages/evpfft-gui/build.sh
Anaconda-Packages/evpfft-gui/meta.yaml
python/.gitignore
python/EVPFFT-GUI/setup.py

Added 
```python
entry_points={
'console_scripts' : [
'evpfft-gui = evpfft_gui.gui:main'
]
}
```
to the setup.py python package definition for EVPFFT-GUI. Installing this package now creates an executable script "evpfft-gui" that you can use on the command line to launch it.

update evpfft gui to include a python entry point

---

scripts/cmake_build.sh

This is my solution to check both lib or lib64 for Trilinos config files. If anyone has another solution, please go ahead. We need to have this fixed ASAP.

Build script will check lib and lib64 folders for Trilinos

---

python/EVPFFT-GUI/evpfft_gui/ui_EVPFFT_GUI_V10.py
python/Voxelizer/CMakeLists.txt
src/Voxelizer/include/stl-to-voxelvtk.h
src/Voxelizer/src/main.cpp
src/Voxelizer/src/stl-to-voxelvtk.cpp

Previously we would always invoke evpfft with relative volume element dimensions: "1. 1. 1.". However, these were never the dimensions, and because of how the voxelizer works (discretizing based on desired number of voxels, not desired voxel size) the actual dimensions were ~unknown and arbitrary.
To fix this we return the dx, dy, and dz from `Voxelizer::create_voxel_vtk` as a tuple. The fierro CLI will just print this out, while the EVPFFT-GUI will actually use those values to make the input file.

Evpfft dimension fix

---

src/Parallel-Solvers/Simulation_Parameters/Geometry.h

Can't compile CUDA code with a throw in it. 
Instead of just _not_ throwing though, which leaves secret incorrect behavior, I am opting to assert(0) instead. This will output an error message to stderr upon host synchronization. I do not believe it actually throws an exception on synchronization, though.
asserting 0 on the device will leave the device memory in an invalid state (i.e. other threads are not guaranteed to resolve correctly). At least we will see that something is wrong and which kernel caused it instead of it silently breaking. This is only used in truly invalid scenarios that should not occur.

Don't throw on the device

---

Anaconda-Packages/voxelizer/meta.yaml
python/EVPFFT-GUI/MANIFEST.in
python/EVPFFT-GUI/evpfft_gui/elastic_parameters.txt

We didn't correctly distribute the "plastic_parameters.txt" file with the evpfft-gui python package. Since we don't actually create that file in the gui program, and we just give it to EVPFFT, its important that actually exists.
So we add those files to the MANIFEST.in, which specifies which non-python files to be included in the package distribution.
Note -- there is a change to elastic_parameters in this commit, but we just overwrite those anyway.

Update package manifests

---

src/Voxelizer/include/RTree.h
src/Voxelizer/src/stl-to-voxelvtk.cpp

Previously to determine if a triangular facet intersects with the ray, we iterated through all of the facets and filtered them based on their bounding box intersection with the ray. If we have M voxels in our 2D iteration and n facets, this is O(M * n). If we instead put them into an RTree first and then check for intersections, it is ~&Theta;(n log(n) + M log(n)) for the tree construction + M queries. 
Note that R-Tree performance is highly data dependent. But because of the typical nature of triangle meshes, we should expect good performance gains over linear search.
Practical testing suggests >10x speed up.
When detecting if a triangle is hit, we use the following algorithm to see if, given consistently oriented triangle vertices (a, b, c) if the chirality of (x, a, b), (x, b, c) and …

Rtree for voxelization

---

scripts/cmake_build.sh

We are trying to `make distclean` if the fierro build folder exists. But, since we use that build folder for building Elements, it can exist before we actually have ever done any cmake things on it, so we might not have a "distclean" target.
So now just kill the build folder if we can't distclean.

Don't distclean if you cant.

---

lib/.gitignore
scripts/hdf5-install.sh
scripts/heffte-install.sh
scripts/trilinos-install.sh
src/EVPFFT/scripts/install-scripts/install_hdf5.sh
src/EVPFFT/scripts/install-scripts/install_heffte.sh
src/EVPFFT/scripts/install-scripts/install_kokkos.sh
src/EVPFFT/scripts/install-scripts/install_matar.sh
src/EVPFFT/src/Fierro-EVPFFT-Link/UserEOSModel.cpp
src/EVPFFT/src/Fierro-EVPFFT-Link/UserEOSModel.h
src/EVPFFT/src/Fierro-EVPFFT-Link/UserStrengthModel.cpp
src/EVPFFT/src/Fierro-EVPFFT-Link/UserStrengthModel.h
src/EVPFFT/src/data_grain.cpp
src/EVPFFT/src/evpal.cpp
src/EVPFFT/src/inverse_the_greens.cpp
src/EVPFFT/src/main.cpp
src/EVPFFT/src/math_functions.cpp
src/EVPFFT/src/math_functions.h
src/EVPFFT/src/write_micro_state.cpp

Since we don't need the history of the repos we clone, I have limited the clones to depth of 1
`git clone --depth 1`
This should save some memory of the cloned repos.
Also, I made the `invert_matrix` function in EVPFFT a templated function because GPUs don't like `new`.
Finally, updated the EVPFFT user material interface to be up to date with Fierro.

depth 1 for all clones, and some changes to EVPFFT folder

---

src/EVPFFT/.gitignore
src/EVPFFT/README.md
src/EVPFFT/scripts/build-scripts/build_evpfft.sh
src/EVPFFT/scripts/install-scripts/install_fftw.sh
src/EVPFFT/scripts/install-scripts/install_hdf5.sh
src/EVPFFT/scripts/install-scripts/install_heffte.sh
src/EVPFFT/scripts/install-scripts/install_kokkos.sh
src/EVPFFT/scripts/install-scripts/install_matar.sh
src/EVPFFT/scripts/machines/linux-env.sh
src/EVPFFT/scripts/machines/mac-env.sh
src/EVPFFT/src/Fierro-EVPFFT-Link/UserEOSModel.cpp
src/EVPFFT/src/Fierro-EVPFFT-Link/UserStrengthModel.cpp

I added --build_fftw and --build_hdf5 options to the EVPFFT build script. This gives more control to the user as to whether to use their own installation of the packages or build it from scratch.
Additionally, I included instructions on how to use the Anaconda package manager to build EVPFFT.

Added build_fftw and build_hdf5 options and how to use Anaconda documentation

---

.conda/README.md
.conda/fierro/cpu/build.sh
.conda/fierro/cpu/meta.yaml
.github/workflows/README.md
.github/workflows/publish-fierro-cpu.yaml
src/CLI/README.md
src/CLI/src/main.cpp

We didn't have a working anaconda package for the fierro cpu builds. It was outdated.
We also didn't have a github action for automatically building fierro-cpu
Now we have a working conda package for fierro-cpu for both OSX and Linux (the usual CPU targets)
+ we have a github action.
I decided against tracking the source code to trigger auto-rebuilding of the packages, since I expect that we don't really want to keep fierro-cpu *that* up to date. For now I have just left you with a manual workflow dispatch trigger + triggering on build metadata change
```yaml
on: 
push:
paths:
- .conda/fierro/cpu/**
- .github/workflows/publish-fierro-cpu.yaml
workflow_dispatch:
```
Bonus -- Added some debugging tips to the Anaconda and Github Actions READMEs
Bonus Bonus -- Added a README to the CLI. So …

Create Fierro-cpu Anaconda Builds + Github Actions

---

src/Yaml-Serializable/README.md
src/Yaml-Serializable/include/yaml-serializable-base.h
src/Yaml-Serializable/include/yaml-serializable-containers.h
src/Yaml-Serializable/include/yaml-serializable.h
src/Yaml-Serializable/test/test.cpp

It was really bugging me that we didn't have usable, native support for fixed length arrays in our auto-serializer. 
Now you can serialize things like `double v[5]` and `std::array<double, 5> v`.
+ The docs are changed to reflect that.
This is great, since it makes it far more likely that you can directly serialize to a GPU serializable type, removing the need to have a special serialization class layer.
Also, you no longer have to use a vector with bespoke length validation to emulate a fixed length array. if you really have a fixed length array, you can just use `T v[N]` and serialize to that + length validation for free.

Implement fixed length serialization for T[N] and array<T, N> things.

---

docs/formatting/README.md
docs/formatting/uncrustify.cfg
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/boundary.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/driver.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/energy_sgh.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/eos.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/force_sgh.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/geometry.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/input.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/mesh.h
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/momentum.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/outputs.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/properties.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/read_mesh.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/setup.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/sgh_solve.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/state.h
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/time_integration.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/user_mat.cpp
single-node/src/Explicit-Lagrange-Kokkos/SGH_solver/user_mat_init.cpp

This PR is a test run of Uncrustify for cleaning up and standardizing formatting in Fierro. I would like to get eyes on by a decent percentage of the team and feedback on what you like and don't like.  Once I have feedback I will update the config and do another pass. 
In the medium to long term, assuming we think it is worth it (I do), I think we should add [Uncrustify](https://github.com/uncrustify/uncrustify) to the build and automate the cleanup process per push. 
* OS version: Rocky Linux
* Hardware: Intel(R) Xeon(R) CPU E5-1630 v3 @ 3.70GHz. NVidia M6000 24GB
* Compiler: gcc 12.2.0

Uncrustify Explicit-Lagrange-Kokkos Files

---

src/Parallel-Solvers/Parallel-Explicit/SGH_Solver/FEA_Module_SGH.cpp
src/Parallel-Solvers/Parallel-Explicit/outputs.cpp
src/Parallel-Solvers/Simulation_Parameters/Output_Options.h

ENH: Added partitioned VTU output option and writer

---

single-node-refactor/regression_tests/test_refactor.py

Added Andrew Morgan's fix to regression script to ensure file times align
Fixes a bug on some computers with python glob , that load files in random order versus a sequential order.
Ran the regression test on Mac, all tests now pass.
- [ X] Test A : ran regression tests
* OS version: MacOS
* Hardware: X86 CPU
* Compiler: clang
- [0] I have added tests that prove my fix is effective or that my feature works
- [0] New and existing unit tests pass locally with my changes
- [0] Any dependent changes have been merged and published in downstream modules

Add Andrew Morgan's fix to regression script to ensure file times align

---

src/EVPFFT/src/evpfft.cpp
src/EVPFFT/src/evpfft.h
src/EVPFFT/src/write_micro_state.cpp
src/LS-EVPFFT/src/allocate_memory.cpp
src/LS-EVPFFT/src/evpfft.cpp
src/LS-EVPFFT/src/evpfft.h
src/LS-EVPFFT/src/update_defgrad.cpp
src/LS-EVPFFT/src/update_grid_velgrad.cpp
src/LS-EVPFFT/src/write_micro_state.cpp

Added a PVTU writer to both the small strain and large strain EVPFFT as well as a space for t=0 output. Also added grain ID as an output field to XDMF writer.
- [ x ] New feature (non-breaking change which adds functionality)
Tested small strain EVPFFT on example uniaxial tension file and large strain EVPFFT on ECAP deformation.
* OS version:
* Hardware:
* Compiler:
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] My changes generate no new warnings
- [ x ] The code builds from scratch with my new changes

EVPFFT Visualization Update

---

src/EVPFFT/src/evpfft.cpp
src/EVPFFT/src/write_micro_state.cpp
src/LS-EVPFFT/src/evpfft.cpp
src/LS-EVPFFT/src/write_micro_state.cpp

Fixed issues with PVTU writer associated with running on GPUs. Also moved the t=0 viz output code to after many inits to ensure fields are defined. 
Adapted GPU incompatible variables to local dual arrays for use within FOR_ALL.
Converted FOR_ALL's within writer to FOR_ALL_CLASS's to use non-local variables correctly.
Ran code on GPUs without crashing at viz output step due to memory issues.

Fix to issues with PVTU writer 12/24

---

src/EVPFFT/src/write_micro_state.cpp
src/LS-EVPFFT/src/evpfft.cpp
src/LS-EVPFFT/src/write_micro_state.cpp

Added code in both small and large strain EVPFFT pvtu writers so that output reflects proper RVE size and spacing from input file. Also fixed code in large strain EVPFFT that was causing non-identity RVE values to produce broken visualizations.
Ran with non-uniform size and spacing RVE lattice and confirmed output visualized correctly.

EVPFFT viz fix for non-cube voxels

---

single-node-refactor/input-impact-erosion.yaml
single-node-refactor/input-lattice.yaml
single-node-refactor/input-noh-rz.yaml
single-node-refactor/input-noh.yaml
single-node-refactor/input-origin-erosion.yaml
single-node-refactor/input-rz-polar.yaml
single-node-refactor/input-rz.yaml
single-node-refactor/input-sgtm-test.yaml
single-node-refactor/input.yaml
single-node-refactor/regression_tests/standard_inputs/Abaqus_read.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov_Erosion.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov_Read_Ensight.yaml
single-node-refactor/regression_tests/standard_inputs/Sedov_rz_polar.yaml
single-node-refactor/regression_tests/standard_inputs/Sod_X.yaml
single-node-refactor/regression_tests/standard_inputs/Sod_Y.yaml
single-node-refactor/regression_tests/standard_inputs/Sod_Z.yaml
single-node-refactor/src/input/parse_yaml.cpp

added solver id to input file, allowing for users to link specified BCs to the correct solver when using multiple solvers.
* OS version: MacOS
* Compiler: clang
- [X ] New and existing unit tests pass locally with my changes

added solver id to input file
